simplification

diff --git a/.github/workflows/tag-require.yml b/.github/workflows/tag-require.yml
--- a/.github/workflows/tag-require.yml
+++ b/.github/workflows/tag-require.yml
@@ -1,11 +1,11 @@
-name: Tag requirement
+name: Check labels
 
 on:
   pull_request:
     types: [opened, labeled, unlabeled, synchronize]
 
 jobs:
-  tag-require:
+  label-require:
     runs-on: ubuntu-latest
     permissions:
       issues: write
@@ -22,29 +22,17 @@ jobs:
             no-tag
           add_comment: true
 
-  semver-require:
+  check-dependent-label:
     runs-on: ubuntu-latest
-    needs: tag-require
+    needs: label-require
     steps:
-      - name: If semver -> check additional tag
+      - name: Check Dependent labels
         run: |
-          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r 'map(.name)')
-          labels_size=$(echo $labels | jq '. | length')
-
-          for label in $(echo $labels | jq -r 'join(" ")'); do
-            case "$label" in
-                major|minor|patch)
-                  if [ $labels_size -ne 2 ]; then
-                    echo "When using major/minor/patch, then you need to specify its prefix using another label!"
-                    exit 1
-                  fi
-                ;;
-                no-tag)
-                  if [ $labels_size -ne 1 ]; then
-                    echo "You can't use 'no-tag' label with another label!"
-                    exit 1
-                  fi
-                ;;
-            esac
-
-          done
+          labels=( $(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -r '.[] | .name') )
+          if [[ ${labels[*]} =~ ^(major|minor|patch)$ && ${#labels[@]} -ne 2 ]]; then
+            echo "When using major/minor/patch, then you need to specify its prefix using another label!"
+            exit 1
+          elif [[ ${labels[*]} == "no-tag" && ${#labels[@]} -ne 1 ]]; then
+            echo "You can't use 'no-tag' label with another label!"
+            exit 1
+          fi
